### ISSUE TITLE
Not working in oneplus one.

### ISSUE THREAD

**Issue by pahapoika** [ViRb3/nMAC#3]
Hey 
i have opo running cyanogenmod 13 nightly.
When i open the latest app it says that Device not supported.

**Comment by ViRb3** [comment]
What is the content of this file: "/persist/WCNSS_qcom_cfg.ini"?
NOTE: Mask your MAC addresses before posting it.

**Comment by pahapoika** [comment]
Mask Mac address??
But there's no WCNSS_qcom_cfg.ini but there's WCNSS_qcom_wlan_nv.bin that contains the code in http://pastebin.com/VzEDSjQ7

**Comment by ViRb3** [comment]
Mask = hide it for security reasons. No wonder the app doesn't work for you - the file that it modifies is missing. I don't know if this is due to an update or something else. Because I do not own an OPO it's impossible for me to figure this out - you'll have to find where your MAC address is stored by yourself.
Please follow this page for more information: https://github.com/ViRb3/nMAC/wiki/Requesting-support-for-a-new-device Feel free to reply here if you've made any progress. Good luck!

**Comment by pahapoika** [comment]
**UPDATE**
My opo broke.
I will buy op3t...
