### ISSUE TITLE
Nexus 5X 7.1.1 - device not supported

### ISSUE THREAD

**Issue by huygn** [ViRb3/nMAC#5]
Rooted with TWRP + SuperSU

**Comment by ViRb3** [comment]
My friend and I have been using it on our 7.1.1 Nexus 5Xs without any problems. Have you ran any other MAC changing tools before mine? There's a big chance they messed something up.

Check this file: **/persist/wlan_mac.bin**
Upload its contents here but **make sure to mask/hide your MAC address** due to privacy reasons.

Good luck!

**Comment by huygn** [comment]
Nope, and I couldn't event found the file, after searching I found this article and it helps: https://chromloop.com/2016/08/how-to-fix-wifi-problem-updating-android-7-0-nougat/

Thanks

**Comment by ViRb3** [comment]
This is exactly what I was about to suggest. Did you manage to re-write your MAC addresses?

**Comment by huygn** [comment]
Nope I edit the file using my old MAC address I got when the phone was on 6

**Comment by ViRb3** [comment]
Does nMAC work for you after that? If not, you should create the file: **/persist/wlan_mac.bin**. Its content should be:

Intf0MacAddress=XXXXXXXXXXXX
Intf1MacAddress=00AA00BB00C2
Intf2MacAddress=00AA00BB00C3
Intf3MacAddress=00AA00BB00C4

Replace the X's with a MAC address. 
Set the file permissions to: **660 (-rw-rw----)** 
Reboot.

nMAC should work afterwards. I don't know about the other file mentioned in the article, **/etc/firmware/wlan/qca_cld/wlan_mac.bin**, as it's empty for me.

**Comment by huygn** [comment]
Yes it works fine 👍
